### PR TITLE
Add Function Calling and response_format

### PR DESCRIPTION
**Pull request by KacperKluka**
### Description

Adjust the SDK to the current latest ([0.1.3](https://github.com/mistralai/client-js/releases/tag/0.1.3)) specification.

### Changes Made

- Renamed the to-be-deprecated `mistral-tiny` to `mistral-small-latest` everywhere in the project
- Added support for the new [Function Calling](https://docs.mistral.ai/guides/function-calling/) feature
- Added support for the `response_format` chat parameter
- Added a working example for the Function Calling feature both in the README and as a dart script

### Checklist

- [+] I have read the [CONTRIBUTING.md](https://github.com/nomtek/mistralai_client_dart/blob/main/CONTRIBUTING.md) document.
- [+] I have tested my changes.
- [+] I have added/updated documentation accordingly.

### CODE REVIEW

**Review by gawi151 — COMMENTED** [review]
What I don't know is that if this will work with chatStream function. Could you double check that?

Otherwise looks nice, GJ 👍

**Comment by KacperKluka** [comment]
> What I don't know is that if this will work with chatStream function. Could you double check that?
> 
> Otherwise looks nice, GJ 👍


Good catch 👍 I've added the support for function calling for stream API https://github.com/nomtek/mistralai_client_dart/pull/37/commits/e624be5462cdfd06992786c407d37e66982c33c9

**Review by gawi151 — APPROVED** [review]
👍

**Review by MarcinGruchala — APPROVED** [review]
LGTM

**Pull request merged**
